(defun encode-direct-count (count lst)
  (cond ((null lst)
         nil)
        ((eql (first lst)
              (first (rest lst)))
         (encode-direct-count (incf count) (rest lst)))
        (t (append (list (list (incf count)
                               (first lst)))
                   (encode-direct-count 0 (rest lst))))))
(defun encode-direct (lst)
  (encode-direct-count 0 lst))
