(defun rotate-n-left (lst n)
  (cond ((zerop n) lst)
        ((> n 0)
         (dotimes (i n lst)
           (setf lst (rest (append lst (list (first lst)))))))
        (t (setf lst (reverse lst))
           (dotimes (i (- n))
             (setf lst (rest (append lst (list (first lst))))))
           (setf lst (reverse lst)))))
