(defun helper (n k s)
  (cond ((= k s) t)
        ((and (> k 1)
              (zerop (mod n k)))
         nil)
        (t (helper n (incf k) s))))
(defun is-prime (n)
  (helper n 2 (1+ (floor (sqrt n)))))
(defun display-prime (n)
  (format t "~A:~A   " n (is-prime n)))
