(defun my-cons (x y)
  (defun dispatch (m)
    (cond ((= m 0) x)
          ((= m 1) y)
          (t (error "m should be 0/1, instead is ~a" m))))
  #'dispatch)
(defun my-car (z)
  (funcall z 0))
(defun my-cdr (z)
  (funcall z 1))
