;(if (eql 1 1)
  ;(progn (write-string "abc"))
  ;(progn (write-string "def")))
(when (> 3 4)
  (princ "I don't think so 1"))
(when (not(> 3 4))
  (princ "I don't think so 1.5"))
(unless (> 3 4)
  (princ "I don't think so 2"))
