(defun solve-triangle (arr n)
  )
(let ((n (read)))
  (dotimes (i n)
    (let* ((size (read))
           (arr (make-array size)))
      (dotimes (j size)
        (dotimes (k (1+ j))
          (setf (aref arr k) (read))))
      (print arr)
      #|(print (solve-triangle arr size))|#)))
