(defun p001 ()
  (loop for i from 1 to 999
     when (funcall #'(lambda (k)
                       (or (zerop (mod k 3))
                           (zerop (mod k 5))))
                   i)
     summing i))
(defun p001-1 ()
  (let ((sum 0))
    (dotimes (i 1000)
      (when (funcall #'(lambda (k)
                         (or (zerop (mod k 3))
                             (zerop (mod k 5))))
                     i)
        (incf sum i)))
    sum))
