(defun sum-3-5-up (n)
  (cond ((> n 20) 0)
        ((or (= (mod n 3) 0)
             (= (mod n 5) 0))
         (+ n (sum-3-5-up (1+ n))))
        (t (sum-3-5-up (1+ n)))))
(defun sum-3-5-down (n)
  (cond ((= n 0) 0)
        ((or (= (mod n 3) 0)
             (= (mod n 5) 0))
         (+ n (sum-3-5-down (1- n))))
        (t (sum-3-5-down (1- n)))))
